-- ============================================================
-- SEED : Catalogue produits TAFDIL (Stock Actuel)
-- Source : Marchandises.pdf — 222 références
-- Doublons de codes PDF : TAFD0026B, TAFD0053B, TAFD0162B
-- ============================================================

INSERT INTO produits (ref, designation, categorie, unite, stock_actuel, stock_min, stock_critique, prix_unitaire_xaf, statut, sync_status)
VALUES
  -- ── Fer plat ──────────────────────────────────────────────
  ('TAFD0001', 'Fer plat de 14',            'metaux', 'barre',   0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0002', 'Fer plat de 16',            'metaux', 'barre',   0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0003', 'Fer plat de 20*3',          'metaux', 'barre',   0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0004', 'Fer plat 20*4',             'metaux', 'barre',   0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0005', 'Fer plat 20*5',             'metaux', 'barre',   0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0006', 'Fer plat 25*3',             'metaux', 'barre',   0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0007', 'Fer plat 25*4',             'metaux', 'barre',   0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0008', 'Fer plat 30*3',             'metaux', 'barre',   0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0009', 'Fer plat 30*4',             'metaux', 'barre',   0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0010', 'Fer plat 30*5',             'metaux', 'barre',   0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0011', 'Fer plat 30*6',             'metaux', 'barre',   0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0012', 'Fer plat 30*6 import',      'metaux', 'barre',   0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0013', 'Fer plat 40*3',             'metaux', 'barre',   0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0014', 'Fer plat 40*4',             'metaux', 'barre',   0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0015', 'Fer plat 40*5',             'metaux', 'barre',   0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0016', 'Fer plat 40*6',             'metaux', 'barre',   0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0017', 'Fer plat 40*8',             'metaux', 'barre',   0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0018', 'Fer plat matelé 30*5',      'metaux', 'barre',   0, 5, 2, 0, 'normal', 'synced'),
  -- ── Fer lisse / carré / en T ──────────────────────────────
  ('TAFD0019', 'Fer lisse de 12',           'metaux', 'barre',   0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0020', 'Fer lisse de 14',           'metaux', 'barre',   0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0021', 'Fer lisse de 10',           'metaux', 'barre',   0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0022', 'Fer carré de 12',           'metaux', 'barre',   0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0023', 'Fer carré tossadé',         'metaux', 'barre',   0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0024', 'Fer carré matellé de 12',   'metaux', 'barre',   0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0025', 'Fer carré de 14',           'metaux', 'barre',   0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0026',  'Fer à T de 25*3',          'metaux', 'barre',   0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0026B', 'Fer à T de 40*3',          'metaux', 'barre',   0, 5, 2, 0, 'normal', 'synced'),
  -- ── Tuyau rond noir ───────────────────────────────────────
  ('TAFD0027', 'Tuyau rond noir 15*21/1,2', 'metaux', 'barre',   0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0028', 'Tuyau rond noir 20*27/1,2', 'metaux', 'barre',   0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0029', 'Tuyau rond noir 20*27/1,5', 'metaux', 'barre',   0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0030', 'Tuyau rond noir 20*27/2',   'metaux', 'barre',   0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0031', 'Tuyau rond noir 26*34/1,2', 'metaux', 'barre',   0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0032', 'Tuyau rond noir 26*34/1,5', 'metaux', 'barre',   0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0033', 'Tuyau rond noir 26*34/2',   'metaux', 'barre',   0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0034', 'Tuyau rond noir 33*42/1,5', 'metaux', 'barre',   0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0035', 'Tuyau rond noir 33*42/2',   'metaux', 'barre',   0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0036', 'Tuyau rond noir 40*49/1,5', 'metaux', 'barre',   0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0037', 'Tuyau rond noir 40*49/2',   'metaux', 'barre',   0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0047', 'Tuyau rond noir 15*21/2',   'metaux', 'barre',   0, 5, 2, 0, 'normal', 'synced'),
  -- ── Tuyau rond galva ──────────────────────────────────────
  ('TAFD0038', 'Tuyau galva rond 15*21/1,5',  'metaux', 'barre', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0039', 'Tuyau rond galva 20*27/1,5',  'metaux', 'barre', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0040', 'Tuyau rond galva 26*34/1,5',  'metaux', 'barre', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0041', 'Tuyau rond galva 33*42/2,5',  'metaux', 'barre', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0042', 'Tuyau rond galva 40*49/1,5',  'metaux', 'barre', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0043', 'Tuyau rond galva 40*49/2,5',  'metaux', 'barre', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0044', 'Tuyau rond galva 33*42/2',    'metaux', 'barre', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0045', 'Tuyau rond galva 20*27/2',    'metaux', 'barre', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0046', 'Tuyau rond galva 15*21/2',    'metaux', 'barre', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0048', 'Tuyau rond galva 40*49/2',    'metaux', 'barre', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0049', 'Tuyau rond russite 20*27/12', 'metaux', 'barre', 0, 5, 2, 0, 'normal', 'synced'),
  -- ── Tube carré ────────────────────────────────────────────
  ('TAFD0050',  'Tube carré 20*1,2',              'metaux', 'barre', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0051',  'Tube carré 25*1,2',              'metaux', 'barre', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0052',  'Tube carré 30*1,2',              'metaux', 'barre', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0053',  'Tube carré 30*1,5',              'metaux', 'barre', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0053B', 'Tube carré 35*1,2',              'metaux', 'barre', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0054',  'Tube carré 35*1,5',              'metaux', 'barre', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0055',  'Tube carré 30*2',                'metaux', 'barre', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0056',  'Tube carré 35*2',                'metaux', 'barre', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0057',  'Tube carré 40*1,5',              'metaux', 'barre', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0058',  'Tube carré 40*2',                'metaux', 'barre', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0059',  'Tube carré matéllé 40*1,5',      'metaux', 'barre', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0060',  'Tube carré matellé 40*2',        'metaux', 'barre', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0061',  'Tube carré 25*1',                'metaux', 'barre', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0062',  'Tube carré 50*1,5',              'metaux', 'barre', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0063',  'Tube carré 40*3',                'metaux', 'barre', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0064',  'Tube carré galva 40*1,5',        'metaux', 'barre', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0065',  'Tube carré matéllé galva 40*1,5','metaux', 'barre', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0066',  'Tube matéllé galva 40*27/1,2',   'metaux', 'barre', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0067',  'Tube carré mattellé 30*1,5',     'metaux', 'barre', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0068',  'Tube carré mattéllé 35*1,5',     'metaux', 'barre', 0, 5, 2, 0, 'normal', 'synced'),
  -- ── Tube rectangulaire ────────────────────────────────────
  ('TAFD0069', 'Tube rectangulaire 40*27/1,2',          'metaux', 'barre', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0070', 'Tube rectangulaire 60*40/2',             'metaux', 'barre', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0071', 'Tube rectangulaire 50*30/1,5',           'metaux', 'barre', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0072', 'Tube rectangulaire 80*40/2',             'metaux', 'barre', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0073', 'Tube rectangulaire matellé galva 40*27', 'metaux', 'barre', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0074', 'Tube rectangulaire galva lisse 40*27/1,2','metaux','barre', 0, 5, 2, 0, 'normal', 'synced'),
  -- ── Cornière ──────────────────────────────────────────────
  ('TAFD0075', 'Cornière 20*2,5',   'metaux', 'barre', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0076', 'Cornière 25*2,5',   'metaux', 'barre', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0077', 'Cornière 30*2,5',   'metaux', 'barre', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0078', 'Cornière 30*3 nor', 'metaux', 'barre', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0079', 'Cornière 35*2,5',   'metaux', 'barre', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0080', 'Cornière 35*3 nor', 'metaux', 'barre', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0081', 'Cornière 35*4',     'metaux', 'barre', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0082', 'Cornière 40*3',     'metaux', 'barre', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0083', 'Cornière 40*4',     'metaux', 'barre', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0084', 'Cornière 45*4',     'metaux', 'barre', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0085', 'Cornière 25*4',     'metaux', 'barre', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0086', 'Cornière 45*3',     'metaux', 'barre', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0087', 'Cornière 30*4',     'metaux', 'barre', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0088', 'Cornière 40*3,5',   'metaux', 'barre', 0, 5, 2, 0, 'normal', 'synced'),
  -- ── Tôle ──────────────────────────────────────────────────
  ('TAFD0089', 'Tôle de 7/10e',  'metaux', 'feuille', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0090', 'Tôle de 8/10e',  'metaux', 'feuille', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0091', 'Tôle de 9/10e',  'metaux', 'feuille', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0092', 'Tôle de 10/10e', 'metaux', 'feuille', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0093', 'Tôle de 12/10e', 'metaux', 'feuille', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0094', 'Tôle de 15/10e', 'metaux', 'feuille', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0095', 'Tôle de 20/10e', 'metaux', 'feuille', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0096', 'Tôle de 30/10e', 'metaux', 'feuille', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0097', 'Tôle de 40/10e', 'metaux', 'feuille', 0, 5, 2, 0, 'normal', 'synced'),
  -- ── Antirouille ───────────────────────────────────────────
  ('TAFD0098', 'Antirouille 1KG Noir',        'peinture', 'bidon', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0099', 'Antirouille 1KG Gris',        'peinture', 'bidon', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0100', 'Antirouille 1KG Rouge',       'peinture', 'bidon', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0101', 'Antirouille 5KG Noir',        'peinture', 'bidon', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0102', 'Antirouille 5KG Gris',        'peinture', 'bidon', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0103', 'Antirouille 5KG Rouge',       'peinture', 'bidon', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0104', 'Antirouille 30KG Noir',       'peinture', 'bidon', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0105', 'Antirouille 30KG Gris',       'peinture', 'bidon', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0106', 'Antirouille 30KG Rouge',      'peinture', 'bidon', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0107', 'Antirouille Ferox 1KG Noir',  'peinture', 'bidon', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0108', 'Antirouille Ferox 1KG Rouge', 'peinture', 'bidon', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0109', 'Antirouille Ferox 5KG Noir',  'peinture', 'bidon', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0110', 'Antirouille Ferox 5KG Rouge', 'peinture', 'bidon', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0111', 'Antirouille metam 1KG',       'peinture', 'bidon', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0112', 'Antirouille vrac noir',        'peinture', 'kg',   0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0113', 'Antirouille vrac rouge',       'peinture', 'kg',   0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0114', 'Antirouille vrac Gris',        'peinture', 'kg',   0, 5, 2, 0, 'normal', 'synced'),
  -- ── Peinture ──────────────────────────────────────────────
  ('TAFD0115', 'Peinture nationale 1KG',       'peinture', 'bidon', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0116', 'Peinture nationale 5KG',       'peinture', 'bidon', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0117', 'Peinture universal 1KG noir',  'peinture', 'bidon', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0118', 'Peinture universal 5KG Gris',  'peinture', 'bidon', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0214', 'Mastic P38',                   'peinture', 'bidon', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0219', 'Spray Paint noir',             'peinture', 'bidon', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0220', 'Spray Paint gris',             'peinture', 'bidon', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0221', 'Spray paint OR',               'peinture', 'bidon', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0222', 'Dorure petit modele',          'peinture', 'bidon', 0, 5, 2, 0, 'normal', 'synced'),
  -- ── Serrures ──────────────────────────────────────────────
  ('TAFD0119', 'Serrure parfait grand modele',     'metaux', 'pièce', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0120', 'Serrure paco grand modele',        'metaux', 'pièce', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0121', 'Serrure paco petit modele',        'metaux', 'pièce', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0122', 'Serrure vachette 1er choix',       'metaux', 'pièce', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0123', 'Serrure vachette 2e choix',        'metaux', 'pièce', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0124', 'Serrure vachette 3e choix',        'metaux', 'pièce', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0125', 'Serrure parfait P1045',            'metaux', 'pièce', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0126', 'Serrure parfait sécurité Perche',  'metaux', 'pièce', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0127', 'Serrure loko',                     'metaux', 'pièce', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0128', 'Serrure Wefara',                   'metaux', 'pièce', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0129', 'Serrure Evalio',                   'metaux', 'pièce', 0, 5, 2, 0, 'normal', 'synced'),
  -- ── Disques diamantés ─────────────────────────────────────
  ('TAFD0130', 'Disque diamanté grand modele',  'metaux', 'pièce', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0131', 'Disque diamanté petit modele',  'metaux', 'pièce', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0132', 'Disque diamanté moyen modèle',  'metaux', 'pièce', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0196', 'Disque à couper',               'metaux', 'pièce', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0197', 'Disque à meuler',               'metaux', 'pièce', 0, 5, 2, 0, 'normal', 'synced'),
  -- ── Paumelles ─────────────────────────────────────────────
  ('TAFD0187', 'Paumelle Maroc lourds 120',  'metaux', 'paquet', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0188', 'Paumelle Maroc lourds 100',  'metaux', 'paquet', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0189', 'Paumelle Maroc lourds 80',   'metaux', 'paquet', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0190', 'Paumelle Maroc leger 120',   'metaux', 'paquet', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0191', 'Paumelle Maroc leger 100',   'metaux', 'paquet', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0192', 'Paumelle Maroc leger 80',    'metaux', 'paquet', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0193', 'Paumelle Maroc 160 lourds',  'metaux', 'paquet', 0, 5, 2, 0, 'normal', 'synced'),
  -- ── Marteaux ──────────────────────────────────────────────
  ('TAFD0194', 'Marteau Emtop gros',   'metaux', 'pièce', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0195', 'Marteau Emtop petit',  'metaux', 'pièce', 0, 5, 2, 0, 'normal', 'synced'),
  -- ── Mètres / rubans ───────────────────────────────────────
  ('TAFD0133', 'Mètre Emtop 5M petit',     'outils', 'pièce', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0134', 'Mètre Emtop 5M gros',      'outils', 'pièce', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0135', 'Mètre Lianjin 5M',         'outils', 'pièce', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0136', 'Mètre 5M jaune',           'outils', 'pièce', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0137', 'Mètre 7,5M',               'outils', 'pièce', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0217', 'Mètre Tiger King 5M',      'outils', 'pièce', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0218', 'Mètre Crocodile 5M',       'outils', 'pièce', 0, 5, 2, 0, 'normal', 'synced'),
  -- ── Cadenas ───────────────────────────────────────────────
  ('TAFD0138', 'Cadenas Top Security', 'outils', 'pièce', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0139', 'Cadenas Royal',        'outils', 'pièce', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0140', 'Cadenas Kinbar',       'outils', 'pièce', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0141', 'Cadenas Yuto',         'outils', 'pièce', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0142', 'Cadenas ABK',          'outils', 'pièce', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0143', 'Cadenas Ciza',         'outils', 'pièce', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0144', 'Cadenas Vajra',        'outils', 'pièce', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0145', 'Cadenas Chaque',       'outils', 'pièce', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0146', 'Cadenas Y*R',          'outils', 'pièce', 0, 5, 2, 0, 'normal', 'synced'),
  -- ── Pinceaux ──────────────────────────────────────────────
  ('TAFD0147', 'Pinceau 30 /paquet', 'outils', 'paquet', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0148', 'Pinceau 40',         'outils', 'pièce',  0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0149', 'Pinceau 50',         'outils', 'pièce',  0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0150', 'Pinceau 60',         'outils', 'pièce',  0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0151', 'Pinceau 70',         'outils', 'pièce',  0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0152', 'Pinceau 100',        'outils', 'pièce',  0, 5, 2, 0, 'normal', 'synced'),
  -- ── Mèches ────────────────────────────────────────────────
  ('TAFD0153', 'Mèche 6',  'outils', 'pièce', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0154', 'Mèche 7',  'outils', 'pièce', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0155', 'Mèche 8',  'outils', 'pièce', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0156', 'Mèche 10', 'outils', 'pièce', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0157', 'Mèche 12', 'outils', 'pièce', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0158', 'Mèche 14', 'outils', 'pièce', 0, 5, 2, 0, 'normal', 'synced'),
  -- ── Flèches ───────────────────────────────────────────────
  ('TAFD0159',  'Flèches fausses', 'outils', 'pièce', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0160',  'Flèches 201',     'outils', 'pièce', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0161',  'Flèches 202',     'outils', 'pièce', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0162',  'Flèches 203',     'outils', 'pièce', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0162B', 'Flèches 204',     'outils', 'pièce', 0, 5, 2, 0, 'normal', 'synced'),
  -- ── Scotch ────────────────────────────────────────────────
  ('TAFD0163', 'Scotch noir',   'outils', 'rouleau', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0164', 'Scotch claire', 'outils', 'rouleau', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0165', 'Scotch jaune',  'outils', 'rouleau', 0, 5, 2, 0, 'normal', 'synced'),
  -- ── Lunettes de soudure ───────────────────────────────────
  ('TAFD0166', 'Lunette de soudure moyen modele', 'outils', 'pièce', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0167', 'Lunette de soudure grand modele', 'outils', 'pièce', 0, 5, 2, 0, 'normal', 'synced'),
  -- ── Canons ────────────────────────────────────────────────
  ('TAFD0168', 'Canons Shiloh',   'outils', 'pièce', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0169', 'Canons Arm',      'outils', 'pièce', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0170', 'Canons Parfait',  'outils', 'pièce', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0171', 'Canons Baglock',  'outils', 'pièce', 0, 5, 2, 0, 'normal', 'synced'),
  -- ── Vis ───────────────────────────────────────────────────
  ('TAFD0172', 'Vis taille 8',    'outils', 'paquet', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0173', 'Vis taille 10',   'outils', 'paquet', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0174', 'Vis taille 12',   'outils', 'paquet', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0175', 'Vis Seiko paquet','outils', 'paquet', 0, 5, 2, 0, 'normal', 'synced'),
  -- ── Équerres ──────────────────────────────────────────────
  ('TAFD0176', 'Équerre moyen modele',  'outils', 'pièce', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0177', 'Équerre long',          'outils', 'pièce', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0178', 'Équerre transparent',   'outils', 'pièce', 0, 5, 2, 0, 'normal', 'synced'),
  -- ── Tournevis ─────────────────────────────────────────────
  ('TAFD0179', 'Tournevis américain', 'outils', 'pièce', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0180', 'Tournevis Total',     'outils', 'pièce', 0, 5, 2, 0, 'normal', 'synced'),
  -- ── Baguettes de soudure ──────────────────────────────────
  ('TAFD0181', 'Baguettes 3,2', 'outils', 'paquet', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0182', 'Baguettes 2,5', 'outils', 'paquet', 0, 5, 2, 0, 'normal', 'synced'),
  -- ── Charbon / meules ──────────────────────────────────────
  ('TAFD0183', 'Charbon petite meule carton',     'outils', 'carton', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0184', 'Charbon petite meule en sachet',  'outils', 'sachet', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0185', 'Charbon sachet transparent',      'outils', 'sachet', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0186', 'Charbon grande meule en sachet',  'outils', 'sachet', 0, 5, 2, 0, 'normal', 'synced'),
  -- ── Papiers abrasifs ──────────────────────────────────────
  ('TAFD0198', 'Papier abrasif vert-jaune /rouleau', 'outils', 'rouleau', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0199', 'Papier abrasif vert-rouge',          'outils', 'rouleau', 0, 5, 2, 0, 'normal', 'synced'),
  -- ── Outillage divers ──────────────────────────────────────
  ('TAFD0200', 'Testeur pièce',             'outils', 'pièce',  0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0201', 'Lame de scie paquet',       'outils', 'paquet', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0202', 'Domino paquet',             'outils', 'paquet', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0203', 'Rivets',                    'outils', 'paquet', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0204', 'Pince à souder pièce',      'outils', 'pièce',  0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0205', 'Attaches sac',              'outils', 'sac',    0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0206', 'Craie industrielle paquet', 'outils', 'paquet', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0207', 'Roulement / galets petit modele', 'outils', 'pièce', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0208', 'Roulement grand modele',    'outils', 'pièce',  0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0209', 'Démarreur',                 'outils', 'pièce',  0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0210', 'Fleur en paire',            'outils', 'paire',  0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0211', 'Tourbillon petit modele',   'outils', 'pièce',  0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0212', 'Tourbillon grand modele',   'outils', 'pièce',  0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0213', 'Rouleaux carton',           'outils', 'carton', 0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0215', 'Verrou 1er choix P136',     'outils', 'pièce',  0, 5, 2, 0, 'normal', 'synced'),
  ('TAFD0216', 'Niveau d''eau',              'outils', 'pièce',  0, 5, 2, 0, 'normal', 'synced')

ON CONFLICT (ref) DO NOTHING;
